#!/bin/sh

set -o errexit

cat > /etc/log_files.yml <<EOF
files:
  - /pt-log/${EXT_USER}
hostname: ${EXT_HOST}
destination:
  host: ${PT_DEST}
  port: ${PT_PORT}
  protocol: tls
EOF

mkdir -p /pt-log
touch "/pt-log/$EXT_USER"

if [ -n "$LISTEN_PORT" ]
then
  nc -lk -p "$LISTEN_PORT" -e /logit &
fi

/remote_syslog/remote_syslog --no-detach=true --poll=true
